### ISSUE TITLE
Problem with PM2 on Windows

### ISSUE THREAD

**Issue by jorgeperegrina** [bevry/watchr#103]
I have a web service that I keep active with PM2 working on a Windows computer. Every time PM2 restarts this service due to a file update, multiple nodejs windows open when I include watchr in a single file. This does not happen using **nodemon** or the **npm start** command. I have already tested this problem by commenting on the lines where I call watchr and saving the file for PM2 to do its job, and no window opens.

This is a portion of my code:

```javascript
const path = require('path'), watchr = require('watchr');
let update = false;
watchr.open(path.join(__dirname, '../views/'), () => { update = true; }, err => { });
```

**Comment by balupton** [comment]
Seems a limitation of Node.js. Use watchman #91 

Could also just be a windows support issue of watchr #341
