### ISSUE TITLE
MaxListenersExceededWarning

### ISSUE THREAD

**Issue by nicoleignasiak** [bevry/watchr#328]
Hello,

I want to implement this file watcher to watch a folder with 100+ subfolders where numerous files get dropped every minute. Right now, I am testing dropping many files into the folder I am watching at a time and I am getting this error: 
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 done listeners added to [TaskGroup]. Use emitter.setMaxListeners() to increase limit

This has happened when I have copied, for example, 7 and 9 and 20 files into the folder location. I can see the watcher registers them all as being created, but I am worried as to why this is causing a memory leak. 
I also get this error when I delete 12 files for example at once.

**Comment by balupton** [comment]
dupe of #97
