### ISSUE TITLE
Change events only fire once

### ISSUE THREAD

**Issue by hbmartin** [bevry/watchr#33]
I'm having a problem change events are only fired once for a given file. I'm running node v0.8.9 on Mac OS X 10.8 Mountain Lion. 
Here's sample output from the included example script:
watching everything completed
a log message occured: { '0': 'debug',
  '1': 'watch event triggered on ui-resizable.css:',
  '2': [ 'change', null ] }
a log message occured: { '0': 'debug',
  '1': 'determined update:',
  '2': 'ui-resizable.css' }
a change event occured: ui-resizable.css

Subsequent updates to the css file display none of these message.
What am I doing wrong?

**Comment by joshcrawmer4** [comment]
I'm still having this Issue. I tried using v2.4.7. But that did not make any difference. fs.watch only recognizes the first change I make to the file. Then after that, nothing happens. I can use echo " " >> filename.txt, and then it works. Please help!

**Comment by tnguyen14** [comment]
Just wanna say that I ran into this issue with using vim and `chokidar`, so I switched over to `watchr` and the issue seems to be gone. Thanks so much for solving it :)
