### ISSUE TITLE
Support glob patterns in paths.

### ISSUE THREAD

**Issue by vjpr** [bevry/watchr#44]
I want to only watch files of certain file extension. Is this possible?

At the moment I'm trying to use `ignoreCustomPatterns` with `/(?!\.rose)$/ig` but I can't seem to get it working.

**Comment by balupton** [comment]
Alright, I've created https://github.com/bevry/ignorefs/issues/2 for this. It is fairly straight forward, although I will need to update each thing that uses `ignorefs` to reflect the changes as it makes sense changing the API a bit for this.

Will get to it after https://github.com/docpad/docpad/issues/1046

**Comment by balupton** [comment]
this is beyond my scope of maintenance, please fund or pr

**Comment by balupton** [comment]
in the upcoming version of watchr, you can provide `ignoreCustomCallback` thanks to the upcoming v5 version of https://github.com/bevry/ignorefs
