### ISSUE TITLE
Removing a single watcher?

### ISSUE THREAD

**Issue by braco** [bevry/watchr#54]
Is there any way to remove a single watch? Don't see anything in the docs about this.

I'm adding files one by one with:
    watchr.watch
      path: single_file
      listeners: ...

and sometimes I need to remove one file's watch. I see .close(), but that seems global.

Alternatively, how can I check if a watch already exists?

**Comment by matthew-dean** [comment]
+1

**Comment by balupton** [comment]
v3.0.0 just released now includes clear documentation on how to do this, sorry it took so long, 2014 and 2015 were hard years for me!

👍
