### ISSUE TITLE
Problems when requiring watchr inside a GruntJS task

### ISSUE THREAD

**Issue by mfidemraizer** [bevry/watchr#57]
I'm having troubles with `watchr` inside GruntJS task.

Once I do a `require("watchr")`, an error is thrown: **Warning: Object 0 has no method 'bind' Use --force to continue.**

It works like a charm in a regular NodeJS module.

Do you have any idea about what's going on with this error?

Thank you in advance!

**Comment by balupton** [comment]
v3.0.0 was just released which is a major rewrite, can you give it a go, as I suspect it will resolve this issue 👍 

Sorry for the late response on this, 2014 and 2015 were hard years for me!
