### ISSUE TITLE
[Linux] watching issues

### ISSUE THREAD

**Issue by as3boyan** [bevry/watchr#63]
I don't understand why but it works fine when I modify file in my node-webkit/atom-shell IDE, when I modify file outside it, for example using `gedit` it stops watching, doesn't report any data.

**Comment by balupton** [comment]
v3.0.0 was just released which is a major rewrite, can you give it a go, as I suspect it will resolve this issue 👍

Sorry for the late response on this, 2014 and 2015 were hard years for me!
