### ISSUE TITLE
Watchr gets stuck and never fires `next` callback when watching wide/nested folders

### ISSUE THREAD

**Issue by ArnaudBrousseau** [bevry/watchr#64]
I ran into this while working with [`docpad`](https://github.com/bevry/docpad/) but I narrowed down this issue to a minimal test case involving `watchr` only.
I secretly suspect it's a bug in [`bal-util`](https://github.com/balupton/bal-util/) but I haven't established this for sure. See "Additional notes" below.

### How to repro
Clone the repo and install/compile:
```
$ git clone git@github.com:bevry/watchr.git
$ cd watchr
$ npm install
$ node_modules/.bin/cake compile
```

Create a new file called `watchr-test-setup`:
```bash
#!/bin/bash
rm -rf watchthis
mkdir watchthis
mkdir watchthis/nested
for i in {1..242}; do touch watchthis/file$i; done;
```
(And `chmod +x watchr-test-setup` to be able to execute it.)

Create a new file called `watchr-test`:
```javascript
var watchr = require('./out/lib/watchr.js');

opts = {
  ignorePaths: false,
  ignoreHiddenFiles: false,
  ignoreCommonPatterns: true,
  ignoreCustomPatterns: false,
  paths: [
    'watchthis'
  ],
  listeners: {
    log: console.log,
    error: function() { console.log('ERROR DETECTED'); },
    change: function() { console.log('CHANGE DETECTED'); }
  },
  next: function() { console.log('DONE'); }
};
var watcher = watchr.watch(opts);
```
Now run:
```
$ ./watchr-test-setup
$ node watchr-test.js
```

### Expected
Watchr watches all the files in the directory and ends its output with `DONE`

### Actual
Watchr watches all the files but hangs at the end. Its `next` callback never gets called:
```
$ node watchr-test.js
debug added a listener: on watchthis for event log
debug added a listener: on watchthis for event error
debug added a listener: on watchthis for event change
debug watch: watchthis
debug added a listener: on watchthis/file1 for event log
debug added a listener: on watchthis/file1 for event change
debug added a listener: on watchthis/file1 for event error
debug added a listener: on watchthis/file10 for event log
debug added a listener: on watchthis/file10 for event change
debug added a listener: on watchthis/file10 for event error
debug watch: watchthis/file1
[snip]
debug added a listener: on watchthis/file99 for event log
debug added a listener: on watchthis/file99 for event change
debug added a listener: on watchthis/file99 for event error
debug watch: watchthis/file99
debug added a listener: on watchthis/nested for event log
debug added a listener: on watchthis/nested for event change
debug added a listener: on watchthis/nested for event error
debug watch: watchthis/nested
[hangs...!]
```

### Additional notes
- I had to binary search for the minimal number of files to repro this issue. If I delete one file (leaving me with 241 files), the issue goes away. This constant (242 in my case) might be hardware specific? FYI I'm running on OSX 10.8.5 with a 1.7 GHz Intel Core i7 and 8 GB of 1600 MHz DDR3 RAM.
- If I delete the `nested` folder, the issue goes away and I can watch as many files as I want (tried with 1000 but I'm sure I could crank it more)
- I tried to dive into the code and I *think* I see a potential culprit in `bal-util`: https://github.com/balupton/bal-util/blob/master/src/lib/paths.coffee#L157. This function is hard to understand so at that point I decided to stop investigating and open this issue. My guess is that there's a race condition.

**Comment by benjie** [comment]
Tip: you can get a canonical URL to a file on GitHub by pressing `y` (see `?` for more keyboard shortcuts) so it'll still point to the same line in the same revision even if the file is updated.

I think the bal-util line referenced above is [this one](https://github.com/balupton/bal-util/blob/4fd340b1ce3d3108860d51c194cec167d27536bc/src/lib/paths.coffee#L157) - the `scandir` method.

**Comment by ArnaudBrousseau** [comment]
@benjie thanks for this tip! Indeed, this is the method I was trying to link to (`scandir`)

**Comment by balupton** [comment]
v3.0.0 was just released which is a major rewrite, can you give it a go, as I suspect it will resolve this issue 👍

Sorry for the late response on this, 2014 and 2015 were hard years for me!
