### ISSUE TITLE
Problem when moving non-empty folder.

### ISSUE THREAD

**Issue by Gwill** [bevry/watchr#66]
If you move a non-empty folder in watching directory, the origin folder and its contained files and folders would emit 'delete' event, but the new folder moved only emit its 'create' event, its contained files and folders wouldn't emit 'create' event.

Is it a bug?

**Comment by ECP-Black** [comment]
Hello,

I have an similar problem under Windows 7/64 with node 0.10.37. When i watch a folder with a structure (e.g.):

/folderA/folderB/fileA.txt
/folderA/folderB/fileB.txt
/folderA/fileA.txt
/fileA.txt

It is not possible to delete folderA. But when I delete FolderB it is possible to delete folderA. 
In general it is not possible to delete folders if the folder contains at least one another folder. When stopping the script i can delete all with out problems.

 Thanks for help,
Dennis

**Comment by balupton** [comment]
Seems like a bug. This has been revised a few times since this issue was originally reported, and v3.0.0 is now out which is a major rewrite. Perhaps it will fix this issue? 👍 

Sorry for the late response on this, 2014 and 2015 were hard years for me!
