### ISSUE TITLE
How can i stop the watching?

### ISSUE THREAD

**Issue by warlley** [bevry/watchr#68]
Hello?! I'm using this library and i have a question. How can i stop the watching? Example: i will need in sometimes, stop the watching and reload the paths to continue watching.

Somebody can help me?

**Comment by matthew-dean** [comment]
+1 - Same question. Is there no "unwatch"?

**Comment by warlley** [comment]
Hello @matthew-dean, this is not a beautiful solution but works for me:

```javascript
var watchrs = [];

var loadWatchrs = function() {
  watchr.watch({
    paths: myPaths,
    listeners: {
      change: function(changeType, filePath, fileCurrentStat, filePreviousStat) {
        proccessFiles(changeType, filePath);
      },
      watching: function(err, watcherInstance, isWatching) {
        // Here we put the watchr on an array
        watchrs.push(watcherInstance);
      }
    }
  });  
};

// Here we can stop the watchrs
watchrs.forEach(function(currentWatchr){
  currentWatchr.close();
});

watchrs = [];

// And... Reload
loadWatchrs();
```

**Comment by balupton** [comment]
3.0.0 just released now includes clear documentation on how to do this, sorry it took so long, 2014 and 2015 were hard years for me!

👍
