### ISSUE TITLE
A faster way to remove watchers?

### ISSUE THREAD

**Issue by matthew-dean** [bevry/watchr#70]
The examples have this structure for closing watchers:
```
for ( i=0;  i<watchers.length; i++ ) {
  watchers[i].close();
}
```
However, for very large directories, this process can take a very long time. Wouldn't there be a faster way to kill all watchers than going through them one by one?

**Comment by matthew-dean** [comment]
Related: I notice that even though I close watchers for specific paths, if I create a new watcher with completely different paths, it "revives" and opens the original watchers. (I'm getting updates for watchers even after I ran the above code to close everything, after I watched a new path.)

**Comment by balupton** [comment]
3.0.0 just released now includes clear documentation on how to do this, sorry it took so long, 2014 and 2015 were hard years for me! 👍
