### ISSUE TITLE
Attach listeners to only directories?

### ISSUE THREAD

**Issue by matthew-dean** [bevry/watchr#71]
Related to #70, maybe I could speed things up if I was only watching create/delete events for directories, and change events only for specific files. How might I use a custom ignore pattern to only watch directories? Or some other configuration switch?

**Comment by balupton** [comment]
This should be possible, however I am not sure how. https://github.com/bevry/scandirectory is the package to look at

Sorry for the late response on this, 2014 and 2015 were hard years for me!

**Comment by balupton** [comment]
This is going to be beyond my scope of maintenance. Please fund or PR.
