### ISSUE TITLE
Doesn't work with Node 0.11.* on Windows

### ISSUE THREAD

**Issue by polkovnikov-ph** [bevry/watchr#73]
Silently fails after several log messages.

**Comment by balupton** [comment]
Node 0.11 is an unsupported version. I've tested v0.8, v0.10, and v0.12, v4, and v6 locally with the latest v3.0.0 release (just released) and works great. Let me know if you still have issues with watchr v3.

Sorry for the late response on this, 2014 and 2015 were hard years for me!
