### ISSUE TITLE
Out of memory error when watching a big folder

### ISSUE THREAD

**Issue by polkovnikov-ph** [bevry/watchr#74]
Starting `watchr` on a big folder results in 1GiB+ memory usage in several minutes and `FATAL ERROR: CALL_AND_RETRY_2 Allocation failed - process out of memory` message.

**Comment by balupton** [comment]
This will happen if `watchFile` method is used and there are a lot of files, as `watchFile` is pretty intensive. Can you give v3.0.0 a go (just released), as it is a major rewrite, and should not encounter the same problems.

Sorry for the late response on this, 2014 and 2015 were hard years for me!
