### ISSUE TITLE
use fswin

### ISSUE THREAD

**Issue by stevenvachon** [bevry/watchr#79]
for better Windows performance:
https://github.com/xxoo/node-fswin/wiki/dirWatcher

**Comment by balupton** [comment]
We'll probably release a version that supports facebook's watchman  #91 as a `preferredMethod` eventually, but not yet.

v3.0.0 was just released that is a major rewrite and should fix a lot of the performance problems. Happy to re-open if not 👍 

Sorry for the late response on this, 2014 and 2015 were hard years for me!
