### ISSUE TITLE
Get path and file name

### ISSUE THREAD

**Issue by vb078** [bevry/watchr#82]
Thank a lot for this eficient folder watcher !

I searching a way to emit over socket.io the fullpath and name of modified files.
But when I use 
```javascript
change: function(changeType,filePath,fileCurrentStat,filePreviousStat){
  console.log('event occured:',arguments);
  socket.emit('message',arguments);
}
```
I just have this log message (client side)

```
[object Object]
```
Maybe you can help :)
THX a lot

**Comment by balupton** [comment]
`arguments` is an object on the client-side, you will have to serialise it to an array I imagine, something like:

```
socket.emit('message', JSON.stringify(Array.prototype.slice.call(arguments)));

**Comment by vb078** [comment]
work great, thx

**Comment by vb078** [comment]
Sorry to re-open it. 
If you have time, its realy great but JSON.stringify all the arguments, I just want to escape fullPath or file name. But, like I say it's great, emmit with socket.io ! Thanks
