### ISSUE TITLE
slow perf on Windows, and throws on basic stuff

### ISSUE THREAD

**Issue by ghost** [bevry/watchr#90]
@balupton Is it possible to watch a single file? I am on windows and keep getting different errors if I try to watch one file. And also ENOENT errors for Windows even if folders exist.

And I noticed the code seems to be slow. It takes around 420ms on my computer - Windows with 32 GB ram - to console log an invoked event when I'm changing file content.

And its seems like this module are eating CPU to breakfest . Now I have 87% load watching a folder with 1 single file.

And could you tell me how to deal with symlinks, and dot files? Are there any options for this?

**Comment by balupton** [comment]
Seems its is following symlnks, and you have symlinks pointing outside, as such Watchr is following it.

I'd suggest using watchman #91 otherwise provide some funding and I'll look into it.

Could also just be a windows support issue of watchr #341
