### ISSUE TITLE
How to watch multiple files with watchr at once?

### ISSUE THREAD

**Issue by steelbrain** [bevry/watchr#93]
I have a usecase where I have an array of files to watch initially and then more files are added and removed from the watcher with `watcher.add(path)` and `watcher.unwatch(path)`. I am currently using `chokidar` but hitting some weird bugs in it (change events triggering twice at once) so looking for an alternative file watcher.

Please note that in my usecase, there's a possibility of adding same path twice with, so add should be noop if path is just being watcher (some modules actually create two fs watchers).

Thank You.

**Comment by balupton** [comment]
> so add should be noop if path is just being watcher (some modules actually create two fs watchers).

correct, only one watchr is made per path
