### ISSUE TITLE
MaxListenersExceededWarning

### ISSUE THREAD

**Issue by crizstian** [bevry/watchr#97]
Hi i am getting the following error, with the basic setup.

Possible EventEmitter memory leak detected. 11 done listeners added. Use emitter.setMaxListeners() to increase limit

**Comment by purportex** [comment]
Please, describe conditions.

**Comment by balupton** [comment]
Limitation of your OS configuration or of Node.js.

Try `ulimit -n 8192` [troubleshooting](https://docpad.bevry.me/start/troubleshoot)

Or use watchman #91
