### ISSUE TITLE
Dependencies old mac

### ISSUE THREAD

**Issue by bonnebulle** [bevry/watchr#98]
Hello.
Great Module for node.js. 
Works great on my fresh mac (10.11.6).
Not on my old one (server v10.6.8). 
I try with the exact same config/code.
Maybe a permission issue. All works fine except for new files (created in the watched folder)
Do you have any idea? 
Thanks
Vincent

**Comment by balupton** [comment]
Closing in favour of https://github.com/bevry/watchr/issues/342
