### ISSUE TITLE
It doesn't work on linux.

### ISSUE THREAD

**Issue by dzek69** [bevry/watchr#99]
I was looking for better alternative to node-watch (as it doesn't differenate `create` from `update`).

So I've implemented basic example on my folder, where ffmpeg constantly saves a stream (so every 500ms a file is modified, every 60 seconds new one is created). And this package can't detect any change there. I've `touch`ed a file in this folder - still nothing.

However - it detects file removal without a problem!

When left for a while - it detected a single change from one of files ffmpeg is saving to (in the middle of the process).

Any suggestions what can be wrong and how to fix it?

**Comment by sbrandwoo** [comment]
Can confirm that on Linux this tool appears to not work. It says it successfully starts watching but then no events will ever be raised.

**Comment by dzek69** [comment]
Use chokidar, the best watching solution for node.js
This one seems dead (no answer in 7 months), I've tested many and most of them are buggy/incomplete/etc. Chokidar seems like the only reliable choice.

**Comment by balupton** [comment]
If it died, it'll be the Node.js core that killed it. I'll look into a maintenance release soon #342 

Otherwise I'd suggest watchman #91
